# Generated by Django 4.0.3 on 2022-04-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
