# Generated by Django 4.0.3 on 2022-04-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cart_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='deliverylocation',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='deliverylocation',
            name='receiver',
        ),
        migrations.AddField(
            model_name='deliverylocation',
            name='address1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='deliverylocation',
            name='address2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='deliverylocation',
            name='post_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
