# Generated by Django 4.0.3 on 2022-04-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_deliverylocation_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverylocation',
            name='address1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='deliverylocation',
            name='address2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='deliverylocation',
            name='post_number',
            field=models.CharField(max_length=10),
        ),
    ]
