# Generated by Django 4.0.3 on 2022-05-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_token_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='personal_info_agreement1',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_info_agreement2',
            field=models.BooleanField(null=True),
        ),
    ]
