# Generated by Django 4.0.3 on 2022-04-25 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Largecategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'large_categories',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='small_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.smallcategory'),
        ),
        migrations.AlterField(
            model_name='smallcategory',
            name='medium_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.mediumcategory'),
        ),
        migrations.AddField(
            model_name='mediumcategory',
            name='large_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.largecategory'),
        ),
    ]
