# Generated by Django 4.0.3 on 2022-05-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_material_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField(null=True, verbose_name='사용자 IP주소')),
            ],
        ),
    ]
