# Generated by Django 4.0.3 on 2022-05-03 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_producthits'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AddField(
            model_name='producthits',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='조회날짜'),
        ),
        migrations.AddField(
            model_name='producthits',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterModelTable(
            name='producthits',
            table='product_hits',
        ),
    ]
