# Generated by Django 4.0.3 on 2022-05-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_hits_producthits_date_producthits_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_rate',
            field=models.IntegerField(null=True),
        ),
    ]
