# Generated by Django 4.0.3 on 2022-05-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_discount_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_rate',
        ),
    ]
