# Generated by Django 4.0.3 on 2022-05-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_discount_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_rate',
            field=models.IntegerField(null=True),
        ),
    ]
